### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by dadaer** [zjunlp/Relphormer#1]
Hi, thanks for sharing the source code! Could you please provide a requirement.txt about library and their versions .I had a big trouble when running the project for the dependency issues.  Thank a lot.

**Comment by zxlzr** [comment]
Hi, thanks for your attention. The code is not fully available now and we will provide the requirement.txt soon.

**Comment by zxlzr** [comment]
The link prediction scripts has been released. We will release other scripts soon.
