### ISSUE TITLE
关于KeyError: 'label'的问题

### ISSUE THREAD

**Issue by quanhangbo** [zjunlp/Relphormer#10]
你好，最近在运行您的代码，Epoch0的features后一半数据是没有lables的，所以Epoch 0 进行到50%的时候，出现KeyError: 'label'，查看了代码后发现是data_module.py的DataCollatorForSeq2Seq类的__init__方法中features处理问题，当lables不存在的时候产生错误，我在运行KNN-KG的时候遇见了同样的问题，请问有什么解决方案吗，错误提示如下：
  File "C:\Users\admin\Desktop\code\Relphormer-main1\Relphormer-main\pretrain\data\data_module.py", line 88, in <listcomp>
    label = [feature.pop("label") for feature in features]
KeyError: 'label'
Epoch 0:  50%|█████     | 10280/20558 [41:37<41:37,  4.12it/s, loss=6.37, v_num=3, hits10=0.000, hits1=0.000]

**Comment by bizhen46766** [comment]
您好，这个问题我们最近会内部复现重跑验证一下。之前做内部测试的时候都正常运行的，有可能是更新包的版本问题处理导致的数据处理错误。

**Comment by bizhen46766** [comment]
你好，上述问题已经解决啦，新的代码版本已经更新。非常抱歉带来不便，如果有新的问题，我们这边会及时更改。
