### ISSUE TITLE
about running time

### ISSUE THREAD

**Issue by sana-mine** [zjunlp/Relphormer#11]
Hello, I am interested in your paper. I would like to ask you about the approximate time for this code to run in each task. How much GPU memory is consumed?

**Comment by bizhen46766** [comment]
It depends on the data size. For dataset such as WN18RR or FB15K237, the whole procedure usually take one or two days in one 3090 gpu (24 GB).

**Comment by sana-mine** [comment]
> It depends on the data size. For dataset such as WN18RR or FB15K237, the whole procedure usually take one or two days in one 3090 gpu (24 GB).

Thanks. But I used your default parameters to test on 'umls' dataset, and found that there is a certain gap between the running results and the paper data. Is there any modification in other parts?
![LW)MX~B5J0}I%U6(}@)0A83](https://user-images.githubusercontent.com/78332751/219331344-4585ae2e-f710-48b8-84ac-f9e18e7a54ec.jpg)

**Comment by bizhen46766** [comment]
Hi, it is caused by the random sampling strategy or pre-training procedure, especially for the small dataset such as UMLS. You can try to pre-train the task with more epochs or use our pre-training checkpoints (which will be attached in this repository).

**Comment by bizhen46766** [comment]
Sorry for the inconvenience.
