### ISSUE TITLE
Issue while saving model for Entity Embedding Initialization

### ISSUE THREAD

**Issue by bhardwaj1230** [zjunlp/Relphormer#13]
Hello.. I was trying to run your repository for UMLS.
I am facing few issues:

1.  I had you git cloned 3 weeks back and the entity embedding part was fine and the I tried to execute **Entity Prediction** but I has issue for tex_d missing from convert_examples_to_features function.  From the reading https://github.com/zjunlp/Relphormer/issues/5 I thought of updating the repo on my end.
2. Now I have updated I am not able to save the model in **Entity Embedding Initialization** where `bash scripts/pretrain_umls.sh` is not saming the best model. The variable `path` desn't have the location to save. 
3. Also when I found the three files features_train.txt features_tvalid.txt and features_test.txt empty for me during this experiment with umls.

Can you please help me with the it and let me know the best way to run your repo for UMLS. My goal is to try it for link prediction for UMLS. Thank you for your repo.

**Comment by bizhen46766** [comment]
Hi Bhardwaj, sorry for the convenience. We have noticed this problem, it was caused by the data module in the pre-training project. We will fix this problem and upload a new version soon.

**Comment by bizhen46766** [comment]
Hi, we have also released the new version, have a try.

**Comment by bhardwaj1230** [comment]
Thank you, I will re-load the new version and try to run it. :)

**Comment by bhardwaj1230** [comment]
Hello @bizhen46766  thank you for your quick responce and helped me to re-run it end to end.
I am now planning to re-run it on a new knowledge graph.
