### ISSUE TITLE
BrokenPipe

### ISSUE THREAD

**Issue by NoviceCrom** [zjunlp/Relphormer#14]
![image](https://user-images.githubusercontent.com/48437212/231687303-98eab136-b864-431f-b4eb-98d650ccb406.png)

BrokenPipe error when running as instructed？

**Comment by bizhen46766** [comment]
Hi,  do the problem occur in the "Entity Prediction" stage?

**Comment by NoviceCrom** [comment]
Yes it is. I've tried to set num_worker=0 according to suggestions on web but didn't work.

**Comment by bizhen46766** [comment]
Hi, sorry for the late reply. We are trying to reproduce this problem and upload the updated code as soon as possible.
