### ISSUE TITLE
链路预测中 HittER 模型在wn18rr数据集上的指标与原文不一致

### ISSUE THREAD

**Issue by Sunrisea** [zjunlp/Relphormer#16]
您好，最近在阅读您的论文，注意到论文中关于hitter模型在WN18RR数据集上的MRR指标为48.5，这不同于 HittER原文中的50.3，请问是什么原因呢，是进行了重新的实验吗？

**Comment by bizhen46766** [comment]
您好，感谢您关注我们的工作！论文里面hitter的结果是进行重新实验的。建议您同时运行Relphormer时也多次取均值，因此随机采样的过程会影响最终的效果。

**Comment by Sunrisea** [comment]
谢谢，另外我想问一下是使用hitter的源码和源码中的配置文件来进行重新实验的吗，还是另外自己实现了呢

**Comment by bizhen46766** [comment]
您好! 是基于hitter的源码来实现的

**Comment by Sunrisea** [comment]
抱歉，我没能太理解您的意思，是直接运行hitter的源码获得的实验结果 还是说重新实现新的代码来进行实验的呢？

**Comment by zxlzr** [comment]
您好是直接基于hitter源码，抱歉看漏了issue回复晚了

**Comment by zxlzr** [comment]
请问您的issue是否已解决？
