### ISSUE TITLE
Question about examples.

### ISSUE THREAD

**Issue by meaningful96** [zjunlp/Relphormer#19]
I have a question about examples.

example file is basically made up of dictionary and there is a key 'en_id'. I thought the 'en_id' corresponds with 'en'. The relation id and entities  are matched, on the other hand the head or tail entities and their id are not matched in example file. Also i don't understand that the length of the fb15k-237 based on the entity2id file is 14541. But i added a line "print(num_entities)" on the processor.py file to check the length of the fb15k-237 is 14951. Could you explain?

**Comment by bizhen46766** [comment]
Hi~ There are a total of 14,541 entity types in dataset FB15K-237. However, the number 14,951 comes from the FB15K dataset, which is larger than the FB15K-237 dataset.
