### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by dadaer** [zjunlp/Relphormer#2]
Hi, another error [Errno 2] No such file or directory: 'dataset/FB15k-237/masked_head_neighbor.txt' occurred after I solved the dependency issue.Actually, there is no such file in dataset.So, I wonder if the project you upload is complete and can be run, if yes, could you tell about how to run it.Thanks!

**Comment by zxlzr** [comment]
Hi, thanks for your attention. The code is not fully available now and we add all those scripts ASAP. Sorry for that.

**Comment by zxlzr** [comment]
The link prediction scripts has been released. We will release other scripts soon.

**Comment by dadaer** [comment]
> The link prediction scripts has been released. We will release other scripts soon.

Thanks!

**Comment by dadaer** [comment]
Hi, there doesn't seem to be any of these files in dataset needed in create_neighbor.ipynb.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/Relphormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月19日(星期三) 上午8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/Relphormer] how to run (Issue #2)





 
The link prediction scripts has been released. We will release other scripts soon.

**Comment by litmirror123** [comment]
> Hi, there doesn't seem to be any of these files in dataset needed in create_neighbor.ipynb.
> 
We will upload these files soon,  thanks for your attention!
