### ISSUE TITLE
似乎现有的pipeline不能跑通

### ISSUE THREAD

**Issue by WEIYanbin1999** [zjunlp/Relphormer#22]
运行更新后的create_neighbors.py,现有的pipeline报错:
![image](https://github.com/zjunlp/Relphormer/assets/127707751/06ff3fe6-bf68-4256-94dd-8e8e7fcbb31a)
似乎是test里没有出现在train里的查询，没有对应的子图储存在masked_neighbor文件中

**Comment by bizhen46766** [comment]
关于pipeline的bug已经解决 非常抱歉给您带来困扰 后续会更新同步上传新的的checkpoint

**Comment by bizhen46766** [comment]
您好项目已经更新呀 如果后续有问题我们也会继续修改迭代

**Comment by zxlzr** [comment]
您好，如果您有任何问题欢迎继续提issue
