### ISSUE TITLE
第一步处理完的masked数据中出现了relation中没有的tmethod_of字段

### ISSUE THREAD

**Issue by HHH-X** [zjunlp/Relphormer#23]

**Comment by HHH-X** [comment]
在python dataset/create_neighbor.py --dataset xxx产生的两个文件中，有一个tmethod_of关系，但是relation中只有method_of关系，请问这是出了什么问题吗

**Comment by bizhen46766** [comment]
你好~ 非常抱歉给您造成困扰 针对生成子图的步骤 我们正在对代码进行修正和更新 后续会上传新的代码

**Comment by bizhen46766** [comment]
您好~ 关于生成子图的步骤的bug我们已经解决了 非常抱歉给您带来麻烦 后续最新的checkpoint我们也会同步上传

**Comment by bizhen46766** [comment]
您好项目已经更新呀 之前运行问题已经解决 如果后续有问题我们会继续修改迭代

**Comment by zxlzr** [comment]
您好，如果您有任何问题欢迎继续提issue
