### ISSUE TITLE
请问是不是没有download.sh文件

### ISSUE THREAD

**Issue by HHH-X** [zjunlp/Relphormer#24]

**Comment by bizhen46766** [comment]
你好，如果huggingface的官网没有办法直接下载模型，可以参考下面的指令下载镜像网站的预训练模型，放在对应文件夹即可
`wget https://hf-mirror.com/bert-base-uncased/resolve/main/config.json`
`wget https://hf-mirror.com/bert-base-uncased/resolve/main/pytorch_model.bin`
`wget https://hf-mirror.com/bert-base-uncased/resolve/main/tokenizer.json`
`wget https://hf-mirror.com/bert-base-uncased/resolve/main/tokenizer_config.json`
`wget https://hf-mirror.com/bert-base-uncased/resolve/main/vocab.txt`

**Comment by HHH-X** [comment]
好的十分感谢

**Comment by bizhen46766** [comment]
目前这个项目正在更新 当前版本可能不太稳定 或者您可以等我们总体更新完之后再运行

**Comment by bizhen46766** [comment]
您好项目已经更新呀  如果后续有问题我们会继续修改迭代
