### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by qixiaonan1** [zjunlp/Relphormer#26]
在运行fb15k.sh文件时出现以下问题，请问这个问题是因为什么呀？该如何解决呜呜呜
问题如下：
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    main()
  File "main.py", line 77, in main
    parser = _setup_parser()
  File "main.py", line 54, in _setup_parser
    model_class = _import_class(f"models.{temp_args.model_class}")    # 通过 _import_class 函数，从 'models' 模块导入指定类，类名由 temp_args.model_class 提供
  File "main.py", line 24, in _import_class
    class_ = getattr(module, class_name)
AttributeError: module 'models' has no attribute 'Relphormer'

**Comment by Hakstar** [comment]
哥们儿 这问题请问怎么解决的呀

**Comment by qixiaonan12** [comment]
> 哥们儿 这问题请问怎么解决的呀

还没解决呢，怎么解决呀呜呜

**Comment by bizhen46766** [comment]
您好呀，有可能是文件的命名问题，我们这边正在复现问题

非常抱歉给您这带来困扰呀，我们这边尽快上传新的代码

**Comment by qixiaonan1** [comment]
> 您好呀，有可能是文件的命名问题，我们这边正在复现问题
> 
> 非常抱歉给您这带来困扰呀，我们这边尽快上传新的代码

请问这个问题有结果了吗？？

**Comment by bizhen46766** [comment]
您好呀 我这边重新跑过之后好像是没问题的 您看是否可以加微信讨论呢 我的微信是bizhen_zju
