### ISSUE TITLE
Would you mind refactoring the code? The structure is very chaotic and it doesn't feel very easy to read

### ISSUE THREAD

**Issue by zhiweihu1103** [zjunlp/Relphormer#3]
as the title

**Comment by zxlzr** [comment]
hello, the code is not available now and sorry for that, we are still cleaning the code, this is a placehoder repro. Sorry for that again.

**Comment by zhiweihu1103** [comment]
Get it.

**Comment by zxlzr** [comment]
The link prediction scripts has been released. We will release other scripts soon.
