### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by qixiaonan12** [zjunlp/Relphormer#31]
您好，在您的数据集中存在text long部分，请问在链接预测任务中该文件是必要的吗？如果必要该文件有何作用，同时我注意到关于KG BERT的数据集中均存在该文件，是否用到BERT均需要该文件？那该文件有何要求吗，是否text中只需要包含实体即可？期待收到您的回答

**Comment by bizhen46766** [comment]
你好呀！text long对应的是文本的描述，因为目前的Relphormer版本是第一步需要对实体关系做初始化，所以需要文本信息；具体文件的要求您可以与我们给的样例文件保持一致就行呀

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
