### ISSUE TITLE
About Triple2Seq part

### ISSUE THREAD

**Issue by zhiweihu1103** [zjunlp/Relphormer#4]
I saw that in the Triple2Seq section, it is mentioned that the neighbors are triple-level, but in the preprocessing code. https://github.com/zjunlp/Relphormer/blob/67a2aab231475b735d95fdce4f59416fc922ef54/dataset/create_neighbor.py#L98 In fact, it is entity-level. For example, for [0, 1, mask_id] and [0, 2, mask_id], the corresponding get_triplet output is exactly the same. If it is triple-level, because the relations of the two triplet are different, and the output should be different. Can you explain this?

**Comment by bizhen46766** [comment]
Thanks for your comments. get_triplet function will generate all neighborhood triplets surrounding the entities. The input to this function is the head or tail entity, not an entity-relation pair.

**Comment by zhiweihu1103** [comment]
Would you mind telling me where entity-relation pair information is involved?

**Comment by bizhen46766** [comment]
My previous reply might cause some confusion and sorry for that. We sample the triplet based on the entity and then generate the relevant triplets. We are not sampling based on entity-relation pair but generate the final outputs in triple-level. Triple2Seq is the process of converting the original triple to a sequence with surrounding contextual triples.

**Comment by bizhen46766** [comment]
Can you add my Wechat so we can have a nice communication?

**Comment by zhiweihu1103** [comment]
OK, no problem.

**Comment by liang-ry** [comment]
> communication
I have some questions about triple2Seq. Can I add your Wechat?

**Comment by bizhen46766** [comment]
Welcome to discuss
