### ISSUE TITLE
Linking prediction

### ISSUE THREAD

**Issue by liang-ry** [zjunlp/Relphormer#5]
Hello, I found the following error while performing a link prediction task, how can I change the code?
![image](https://user-images.githubusercontent.com/46769839/196939365-4ac1ffb8-9ee0-4f29-83f7-89055836f0df.png)

**Comment by litmirror123** [comment]
> Hello, I found the following error while performing a link prediction task, how can I change the code? ![image](https://user-images.githubusercontent.com/46769839/196939365-4ac1ffb8-9ee0-4f29-83f7-89055836f0df.png)

Hi, we have updated data/processor.py and you can update this file to rerun the task. Thanks for your attention!

**Comment by bhardwaj1230** [comment]
I am this issue too. text_d is is not from convert_examples_to_features function. Is there a fix for it?
