### ISSUE TITLE
Entity Embedding Initialization 

### ISSUE THREAD

**Issue by mqEpiphany** [zjunlp/Relphormer#6]
Hello, I found the following error while performing entity embedding initialization, how can I change the code?
![image](https://user-images.githubusercontent.com/79396680/206134780-3ac16ac7-3514-4e6d-b454-f70d4a5f8407.png)

**Comment by bizhen46766** [comment]
Hello, you can try to run the python file with single GPU

**Comment by mqEpiphany** [comment]
I only have one gpu

**Comment by bizhen46766** [comment]
Is your CUDA available in the current python interpreter setting?
you can check by the code, torch.cuda.is_available()

**Comment by mqEpiphany** [comment]
![image](https://user-images.githubusercontent.com/79396680/206180715-26e08b06-a011-4903-b0f0-a3a95c66ae8e.png)

**Comment by bizhen46766** [comment]
Hi, I think this problem might be caused by the inaccurate use of the cuda device. 
You can first check the pytorch_lightning  package version and then make sure the correct use of cuda id.

**Comment by mqEpiphany** [comment]
Thanks for your help, I have solved this problem by modifying the code of transformers/tokenization utils base.py
